apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-ibm-odm-ibm-odm-dev
spec:
  destination:
    namespace: gitops-ibm-odm
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/gitops-ibm-odm/ibm-odm-dev
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-ibm-odm
    targetRevision: main
    helm:
      releaseName: ibm-odm-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
