apiVersion: v1
kind: Namespace
metadata:
  name: gitops-ibm-odm
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitops-ibm-odm-operator-group
  namespace: gitops-ibm-odm
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  targetNamespaces:
    - gitops-ibm-odm
---
