apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-ibm-odm-ibm-odm-dev-ibm-odm-dev-sa
spec:
  destination:
    namespace: gitops-ibm-odm
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: >-
      payload/1-infrastructure/namespace/gitops-ibm-odm/ibm-odm-dev-ibm-odm-dev-sa
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-ibm-odm
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - jsonPointers:
        - /imagePullSecrets
        - /secrets
      kind: ServiceAccount
